export const SET_SIGN_IN_SUCCESSFUL = "SET_SIGN_IN_SUCCESSFUL";
export const SET_SIGN_UP_SUCCESSFUL = "SET_SIGN_UP_SUCCESSFUL";
export const SET_AUTH_FAILED = "SET_AUTH_FAILED";
export const SET_LOADING = "SET_LOADING";
export const SET_LOGOUT = "SET_LOGOUT";
export const SET_REFRESH = "SET_REFRESH";

export const SET_SCHOOL_INFO_SUCCESSFUL = "SET_SCHOOL_INFO_SUCCESSFUL"
export const SET_SCHOOL_INFO_FAILED = "SET_SCHOOL_INFO_FAILED"

export const SET_RATING_SUCCESSFUL = "SET_RATING_SUCCESSFUL"
export const SET_RATING_FAILED = "SET_RATING_FAILED"

export const SET_LIBRARY_SUCCESSFUL = "SET_LIBRARY_SUCCESSFUL"
export const SET_LIBRARY_FAILED = "SET_LIBRARY_FAILED"

export const SET_VACANCY_SUCCESSFUL = "SET_VACANCY_SUCCESSFUL"
export const SET_VACANCY_FAILED = "SET_VACANCY_FAILED"