export const SET_SIGN_UP_SUCCESSFUL = "SET_SIGN_UP_SUCCESSFUL";
export const SET_SIGN_UP_FAILED = "SET_SIGN_UP_FAILED";
export const SET_SIGN_UP_LOADING = "SET_SIGN_UP_LOADING";

export const SET_SIGN_IN_SUCCESSFUL = "SET_SIGN_IN_SUCCESSFUL";
export const SET_SIGN_IN_FAILED = "SET_SIGN_IN_FAILED";
export const SET_SIGN_IN_LOADING = "SET_SIGN_IN_LOADING";

