export const SET_SIGN_IN_SUCCESSFUL = "SET_SIGN_IN_SUCCESSFUL";
export const SET_SIGN_UP_SUCCESSFUL = "SET_SIGN_UP_SUCCESSFUL";
export const SET_AUTH_FAILED = "SET_AUTH_FAILED";
export const SET_LOADING = "SET_LOADING";
export const SET_LOGOUT = "SET_LOGOUT";
export const SET_REFRESH = "SET_REFRESH";